variables:
  VSWHERE_PATH: '%ProgramFiles(x86)%\Microsoft Visual Studio\Installer\vswhere.exe'
  NUGET_PACKAGES: 'C:\NugetPackageCache'
  XUNIT_PATH: 'C:\Tools\xUnitRunner\xunit.console.exe'
  # Максимальное количество параллельно собираемых проектов при сборке решения; 
  # зависит от количества ядер ПК, выбранного для сборки
  MSBUILD_CONCURRENCY: 4
  BUILD_FOLDER: 'FriendStorage.UI\bin\Release'
  TEST_FOLDER: 'FriendStorage.UITests\bin\Release'

.before_msbuild: &enter_vsdevshell
  before_script:
    - chcp 65001
    - '$vsWherePath = [System.Environment]::ExpandEnvironmentVariables($env:VSWHERE_PATH)'
    - '& $vsWherePath -latest -format value -property installationPath -products Microsoft.VisualStudio.Product.Community Microsoft.VisualStudio.Product.BuildTools | Tee-Object -Variable visualStudioPath'
    - 'Join-Path "$visualStudioPath" "\Common7\Tools\Microsoft.VisualStudio.DevShell.dll" | Import-Module'
    - 'Enter-VsDevShell -VsInstallPath:"$visualStudioPath" -SkipAutomaticLocation'

stages:
  - build
  - test

build_job:
  <<: *enter_vsdevshell
  stage: build
  tags: [dotnetcicdtest]
  only:
    - /^master$/
  script:
    - 'msbuild /t:restore /p:Configuration="Release" /p:Platform="Any CPU" /m:$env:MSBUILD_CONCURRENCY /nr:false /clp:ErrorsOnly'
    - 'msbuild /p:Configuration="Release" /p:Platform="Any CPU" /m:$env:MSBUILD_CONCURRENCY /nr:false /clp:ErrorsOnly'
  artifacts:
    name: "master_$($CI_PIPELINE_IID)"
    expire_in: 28 days
    paths:
      - "$env:BUILD_FOLDER\\*.dll"
      - "$env:BUILD_FOLDER\\*.config"
      - "$env:BUILD_FOLDER\\*.exe"
      - "$env:TEST_FOLDER\\*.dll"
      - "$env:TEST_FOLDER\\*.config"
      - "$env:TEST_FOLDER\\*.exe"
      
test_job:
  stage: test
  tags: [dotnetcicdtest]
  only:
    - /^master$/
  script:
    - '& "$env:XUNIT_PATH" "$env:TEST_FOLDER\FriendStorage.UITests.dll"'
  dependencies:
    - build_job